import Head from "next/head";
import { DocumentHeadTags } from "@mui/material-nextjs/v13-pagesRouter";

import { RRuleBuilder } from "react-rrule-builder-ts";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFnsV3";

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <DocumentHeadTags {...props} />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>RRuleBuilder Test</h1>
        <RRuleBuilder dateAdapter={AdapterDateFns} />
      </div>
    </>
  );
}
